[platformio]

[env:flash-nuke]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = generic_rp2350
framework = picosdk
extra_scripts = post:copy_to_ram.py
build_src_filter =
  -<*>
  +<nuke.c>
build_flags =
  -DPICO_FLASH_SIZE_BYTES=33554432
  -DPICO_COPY_TO_RAM=1
