[platformio]
src_dir = .

[env:pi2350]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = generic_rp2350
framework = arduino
lib_deps =
    adafruit/Adafruit GFX Library@^1.12.1
    adafruit/Adafruit NeoPixel@^1.12.4
    https://github.com/ctag-fh-kiel/Adafruit_TinyUSB_Arduino.git#fix/usb_host_arturia_bspro
    https://github.com/rppicomidi/usb_midi_host.git#1.1.4

build_flags = -DUSE_TINYUSB -DUSE_TINYUSB_HOST -DARDUINO_VARIANT_CHIP=RP2530B
board_build.core = earlephilhower
monitor_speed = 115200

[env:tests]
platform = native
build_src_filter =
    +<MidiParser.cpp>
test_framework = googletest
