[platformio]

[env:pi2350]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = generic_rp2350
framework = arduino
lib_deps =
    https://github.com/ctag-fh-kiel/Adafruit_TinyUSB_Arduino.git#fix/usb_host_arturia_bspro
    adafruit/Adafruit GFX Library@^1.12.1
    https://github.com/ctag-fh-kiel/DaDa_OLED.git#v1.0.0
build_src_filter =
  -<*>
  +<../examples/>
build_flags = -DUSE_TINYUSB
board_build.core = earlephilhower
monitor_speed = 115200
