name: build tbd firmware

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Run Unit Tests
        run: pio test -e tests

      - name: Build Firmware
        run: pio run -e pi2350

      - name: Upload Firmware
        uses: actions/upload-artifact@v4
        with:
          name: tbd_frontend
          path: |
            .pio/build/pi2350/firmware.bin
            .pio/build/pi2350/firmware.uf2
          overwrite: true